# Generated by Django 2.2.5 on 2019-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dogtag_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogtag',
            name='dog_tag_color',
            field=models.TextField(default='goldenrod'),
            preserve_default=False,
        ),
    ]
